name: Zimmerman
favicon: null
layout_spectrum: 0.47633813228458166
typography_spectrum: 0.46008802484720945
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.42768006143160164
  lightness: 0.07689286954700947
  saturation: 0.4270189490634948
  rhythmicContrast: 0.14149334654211998
purpose: []
